---
title: "8 - Age adjusted associations (age cat)"
author: "Luis Segura"
date: "2024-09-11"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

options(tinytex.verbose = TRUE, scipen = 999)

mypckgs <- c("tidyverse", "here", "survey", "srvyr", "doParallel", "foreach", 
             "emmeans", "extrafont", "showtext", "patchwork")

for (package in mypckgs) {
  library(package, character.only = T)
}

## setup parallel processing
no_cores <- detectCores() - 1  
cl <- makeCluster(no_cores)
registerDoParallel(cl)
getDoParWorkers()                   
getDoParName()

loadfonts(device = "win")

font_add(family = "Times New Roman", regular = "times.ttf")
showtext_auto()

```


```{r}
### leemos la base de datos
load(here("data/", "ensanut18_4analysis.RData"))
```

```{r}
### Creamos el objeto del diseño muestral para calcular los estimadores ponderados (p.ej., prevalencias)
ensanut_diseno <- ensanut18_4analysis |>
  as_survey_design(strata = est_dis, 
                   ids = upm_dis, 
                   weights = f_20mas, 
                   nest = T)
```

```{r}
adj_estimates_fun <- function(x, y, z){
  
  reference <- ensanut18_4analysis |>
    pull(!!sym(x)) |> 
    levels()
  
  reference <- reference[1]
  
  my_formula <- as.formula(str_glue("{y} ~ {x} + {z}"))
  
  fit <- svyglm(my_formula, design = ensanut_diseno, family = quasipoisson) 
  
  fit_emm <- fit |>
    emmeans(as.formula(str_glue("trt.vs.ctrl ~ {x}")), var = x, type = "response", 
            data = ensanut18_4analysis) 

  contrasts_emm <- fit_emm |>
    pluck("contrasts") |>
    broom::tidy(conf.int = T) |>
    select(var = term, contrast, PR = ratio, conf.low, 
           conf.high, `p value` = ends_with("p.value")) 
  
  model_estimates <- tibble(var = x, 
         contrast = c(str_glue("{reference} (REF)"), 
                      str_extract(contrasts_emm |> pull(contrast), "^[^/]+")),
         PR = c(1, contrasts_emm |> pull(PR)), 
         conf.low = c(NA, contrasts_emm |> pull(conf.low)), 
         conf.high = c(NA, contrasts_emm |> pull(conf.high)), 
         `p value` = c(NA, contrasts_emm |> pull(`p value`)))
  
    adj_prop <- fit_emm |>
    pluck("emmeans") |>
    as_tibble() |>
    mutate(var = x, 
           prop = rate * 100, 
           conf_low = asymp.LCL * 100, 
           conf_high = asymp.UCL * 100) |>
    select(var, term = !!sym(x), prop, conf_low, conf_high)

  list(adj_prop = adj_prop, model_estimates = model_estimates)

}


```

```{r}
svi_prop <- svyglm(disc_visual_severa_num ~ age_cat, 
                   design = ensanut_diseno, family = quasipoisson) |>
  emmeans::emmeans(specs = ~ 1, type = "response", 
                   data = ensanut18_4analysis) |>
  broom::tidy()
```

The age adjusted prevalence of SVI is `r svi_prop |> pull(rate) |> mutate(rate * 100)`%
```{r}
var_char <- names(ensanut18_4analysis)[c(6, 8, 14:19, 44)]


tab_estimates <- foreach(i = var_char, 
                     .packages = c("tidyverse", "emmeans", 
                                   "survey", "srvyr")) %dopar% {
  adj_estimates_fun(i, "disc_visual_severa_num", "age_cat")
}

# save(tab_estimates, file = here("data/", "age_adjusted_estimates_v2.RData"))

```


```{r}
tab_est_coefs <- map(tab_estimates, "model_estimates") |>
  bind_rows()

# write_csv(tab_est_coefs, here("results/", "tab_est_coefs_age_cat_adj.csv"))

### Figure 1. Sociodemographic predictor of Severe Visual Impairment among the Mexican population.
plot <- tab_est_coefs |>
  rename(term = contrast) |>
  mutate(term = str_trim(term, side = "both")) |>
  mutate(term = case_when(var == "l_indigena" & term == "No (REF)" ~ "Doesn't speak indigenous language (REF)", 
                          var == "l_indigena" & term == "Yes" ~ "Speaks indigenous language", 
                          var == "insurance" & term == "No insurance (REF)" ~ "Uninsured (REF)", 
                          var == "insurance" & term == "Insurance" ~ "Insured",
                          var == "work_pwk" & term == "Yes (REF)" ~ "Past-week employed (REF)", 
                          var == "work_pwk" & term == "No" ~ "Past-week unemployed",
                          var == "diab_hbp" & term == "No diabetes or HTN (REF)" ~ "Neither diabetes nor hypertension (REF)", 
                          var == "diab_hbp" & term == "Diabetes no HTN" ~ "Diabetes / no hypertension",
                          var == "diab_hbp" & term == "HTN no diabetes" ~ "Hypertension / no diabetes",
                          var == "diab_hbp" & term == "Both diabetes & HTN" ~ "Diabetes & hypertension",
                          T ~ term), 
         term =  factor(term),  
         orden = seq(1, length(var), 1),
         color = factor(c(rep(1, 2), rep(2, 4), rep(3, 2), rep(4, 4), 
                   rep(5, 3), rep(6, 2), rep(7, 2), rep(8, 2), rep(9, 4)), 
                   labels = c("Sex", "Region", "Urbanicity", "Education", 
                              "SES", "Insurance", "Indigenous", "PW employment", 
                              "Diabetes and hypertension"))) |>
  ggplot(aes(y = reorder(ordered(interaction(term, color, sep = "!")), desc(orden)), 
             x = PR, xmin = conf.low, xmax = conf.high, color = color)) +
  geom_point(size = 5, shape = "diamond") +
  geom_errorbarh(height = 0.3) + 
  scale_x_continuous(limits = c(0.2, 5.0), breaks = c(0.7, seq(1.0, 5.0, 1.0)), name = "Prevalence Ratio (95% CI)")  +
  scale_y_discrete(guide = ggh4x::guide_axis_nested(delim = "!")) +
  geom_vline(xintercept = 1, color = "black", linetype = "solid", alpha = 0.5) +
  ggthemes::theme_calc() +
  theme(legend.position = "none", 
        plot.caption = element_text(size = 10, family = "Times New Roman", face = "bold", hjust = 0), 
        plot.title = element_text(size = 10, family = "Times New Roman"), 
        text = element_text(size = 10, family = "Times New Roman"), 
        plot.margin = margin(5, 5, 5, 5), 
        panel.background = element_rect(fill = "transparent", color = NA), 
        plot.background = element_rect(fill = "transparent", color = NA)) +
  labs(y = "",
       title = "") 

figure_1 <- plot + plot_annotation(caption = "Figure 1. Age-adjusted associations between sociodemographic characteristics, diabetes and/or hypertension, and severe vision impairment among Mexican adults. ENSANUT 2018.\nSES: Socioeconomic status. PW: past-week. REF: reference level. yo: years old. HTN: Hypertension.\nPrevalence Ratios are age-adjusted", 
                                   theme = theme(plot.caption = element_text(hjust = 0, size = 10, face = "bold", family = "Times New Roman"),
      plot.margin = margin(5, 20, 20, 5)))

ggsave(here("results/", "forestplot_age_cat_adj_v2.pdf"), plot = figure_1,
       width = 12, height = 7, device = cairo_pdf, units = "in", dpi = 1800, bg = "transparent")

ggsave(here("results/", "forestplot_age_cat_adj_v2.jpeg"), plot = figure_1,
       width = 12, height = 6, units = "in", dpi = 1800)

```

